const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const context={window:{},fetch:()=>{},AbortSignal,URLSearchParams};vm.createContext(context);vm.runInContext(fs.readFileSync('dist/planner.js','utf8'),context);const p=context.window.TravelPlanner;
const center={lat:37.56,lng:126.98};const places=Array.from({length:12},(_,i)=>({id:String(i),name:'Stop '+i,lat:37.56+i*.001,lng:126.98+(i%3)*.003,duration:75}));
const before=JSON.stringify(places);const planned=p.plan({places,center,days:3,perDay:4});assert.equal(planned.length,3);assert.equal(planned.flatMap(d=>d.items.filter(i=>!i.place.pendingMeal)).length,12);assert.equal(new Set(planned.flatMap(d=>d.items.filter(i=>!i.place.pendingMeal).map(i=>i.place.id))).size,12);assert.equal(JSON.stringify(places),before);assert(planned.every(d=>d.items.every(i=>/^\d{2}:\d{2}$/.test(i.time))));
assert.throws(()=>p.plan({places,center,days:0,perDay:4}));const dedup=p.plan({places:[places[0],places[0],{id:'bad',lat:999,lng:0}],center,days:1,perDay:4});assert.equal(dedup[0].items.filter(i=>!i.place.pendingMeal).length,1);
const shuffled=[places[11],places[0],places[9],places[2]];assert(p.routeLength(p.improve(shuffled,center),center)<=p.routeLength(shuffled,center));
vm.runInContext(fs.readFileSync('dist/map-providers.js','utf8'),context);assert.equal(context.window.TravelMaps.providerFor('KR'),'naver');for(const code of ['FR','US','JP','GB','AU','DE'])assert.equal(context.window.TravelMaps.providerFor(code),'google');
vm.runInContext(fs.readFileSync('dist/stories.js','utf8'),context);vm.runInContext(fs.readFileSync('dist/stories-ko.js','utf8'),context);for(const id of Object.keys(context.window.PLACE_STORIES)){assert.equal(context.window.PLACE_STORIES[id].chapters.length,context.window.PLACE_STORIES_KO[id].chapters.length);assert(context.window.PLACE_STORIES[id].sources.every(s=>s.url.startsWith('https://')))}
console.log('PASS: trip grouping, unique stops, non-mutating input, time format, validation, route improvement, country dispatch, bilingual chapter parity.');
const toolContext={window:{},document:{addEventListener(){}},localStorage:{getItem(){return null}},Intl,URLSearchParams,AbortSignal,fetch:()=>{},navigator:{}};vm.createContext(toolContext);vm.runInContext(fs.readFileSync('dist/utilities.js','utf8'),toolContext);const helpers=toolContext.window.TravelTools;const france=helpers.render({destination:{country:'FR',center:{lat:48.85,lng:2.35}},city:'Paris'});assert(france.includes('Trip suggestion · EUR'));assert(france.includes('French'));assert(france.includes('currency-from')&&france.includes('currency-to'));const korea=helpers.render({destination:{country:'KR',center:{lat:37.56,lng:126.97}},city:'Seoul'});assert(korea.includes('Trip suggestion · KRW'));assert(korea.includes('Korean'));assert.equal(Object.values(helpers.languages).every(l=>l.phrases.length===4&&l.voice),true);console.log('PASS: configurable currency controls, country defaults, and pronunciation data.');

const longDay=p.plan({places:Array.from({length:20},(_,i)=>({id:'long'+i,lat:37.56+i*.0001,lng:126.98,duration:60})),center,days:1,perDay:12,endHour:21});assert(longDay[0].items.length>4);assert(longDay[0].items.at(-1).time>='19:00');assert(longDay[0].items.every(i=>{const [h,m]=i.time.split(':').map(Number);return h*60+m+60<=21*60}));assert.throws(()=>p.plan({places,center,days:1,startHour:10,endHour:9}));console.log('PASS: full-day plans continue into evening and respect the chosen finish time.');

const unlimited=p.plan({places:Array.from({length:30},(_,i)=>({id:'short'+i,lat:37.56,lng:126.98,duration:15})),center,days:1,startHour:6,endHour:23});assert(unlimited[0].items.length>12);console.log('PASS: no daily place-count cap.');

const timedPlaces=Array.from({length:30},(_,i)=>({id:'timed'+i,lat:37.56,lng:126.98,duration:60}));const early=p.plan({places:timedPlaces,center,days:1,startHour:9,endHour:14.5,pace:1.2})[0].items;const late=p.plan({places:timedPlaces,center,days:1,startHour:9,endHour:21,pace:1.2})[0].items;assert(late.length>early.length);assert(early.every(i=>{const [h,m]=i.time.split(':').map(Number);return h*60+m+i.duration<=870}));console.log('PASS: custom finish time changes itinerary length and includes visit duration.');
const foodPlaces=[...timedPlaces,...['Restaurant','Restaurant','Café'].map((type,i)=>({id:'food'+i,type,name:type,lat:37.56,lng:126.98,duration:60}))];const foodDay=p.plan({places:foodPlaces,center,days:1,startHour:9,endHour:21})[0];assert.deepEqual(Array.from(foodDay.items.filter(i=>i.label!=='Sightseeing'),i=>i.label),['Lunch','Café break','Dinner']);assert(foodDay.items.length>4);assert.equal(foodDay.missing.length,0);assert.equal(new Set(foodDay.items.map(i=>i.place.id)).size,foodDay.items.length);const noFood=p.plan({places:timedPlaces,center,days:1})[0];assert.equal(noFood.missing.length,3);console.log('PASS: real restaurants and café inserted at meal times; no duplicates; missing options reported.');

const statue=p.details({id:'statue',source:'OpenStreetMap',tags:{historic:'memorial'},duration:60},'GB');const museum=p.details({id:'museum',source:'OpenStreetMap',tags:{tourism:'museum'},duration:60},'GB');assert.equal(statue.duration,15);assert.equal(museum.duration,120);assert.equal(p.budget(museum,'GB').currency,'GBP');assert.equal(p.budget(museum,'GB').kind,'unknown');assert.equal(p.budget({...museum,feeFree:true},'GB').high,null);assert.equal(p.budget(museum,'ZZ').currency,'GBP');assert.equal(p.budget({type:'Museum'},'ZZ').low,null);const london=p.plan({places:p.highlights,center:{lat:51.5074,lng:-.1278},days:3,country:'GB',pace:1.2});assert(london.some(d=>d.items.some(i=>i.place.id==='london-british-museum')));for(const d of london){let last=0;for(const i of d.items){const [h,m]=i.time.split(':').map(Number);assert(h*60+m>=last);last=h*60+m+i.duration;assert(last<=1260);assert.notEqual(i.duration,72)}}console.log('PASS: category-specific durations, GBP budgets, unknown-price handling, major London visits, non-overlapping schedules.');

for(const type of ['Sight','Museum','Restaurant','Café','Monument'])assert.equal(p.budget({type,cost:0},'GB').low,null);const tower=p.highlights.find(p=>p.id==='london-tower');for(const pace of [1,1.2,1.5]){const plannedTower=p.plan({places:[tower],center:tower,days:1,country:'GB',pace})[0].items.find(i=>i.place.id===tower.id);assert.equal(plannedTower.duration,180)}assert.equal(p.budget(tower,'GB').kind,'listed');console.log('PASS: no invented budget ranges; sourced Tower duration stays 180 minutes at every pace.');
